In [ ]:
# Connecting to google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install transformers accelerate bitsandbytes llama-index-llms-huggingface

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Collecting llama-index-llms-huggingface
  Downloading llama_index_llms_huggingface-0.7.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.25.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.6.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Collecting llama-index-core<0.15,>=0.13.0 (from llama-index-llms-huggingface)
  Downloading llama_index_core-0.14.18-py3-none-any.whl.metadata (2.6 kB)
Collecting transformers
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 2.2 MB/s eta 0:00:00
Collecting huggingface_hub>=0.21.0 (from accelerate)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.4.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: aiohttp<4,>=3.8.6 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (3.13.3)
Requirement already satisfied: aiosqlite in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (0.22.1)
Collecting banks<3,>=2.3.0 (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface)
  Downloading banks-2.4.1-py3-none-any.whl.metadata (12 kB)
Collecting dataclasses-json (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting deprecated>=1.2.9.3 (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface)
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting dirtyjson<2,>=1.0.8 (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface)
  Downloading dirtyjson-1.0.8-py3-none-any.whl.metadata (11 kB)
Collecting filetype<2,>=1.2.0 (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: httpx in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (0.28.1)
Collecting llama-index-workflows!=2.9.0,<3,>=2 (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface)
  Downloading llama_index_workflows-2.16.1-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: nest-asyncio<2,>=1.5.8 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (3.6.1)
Requirement already satisfied: nltk>3.8.1 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (3.9.1)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (11.3.0)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (4.9.4)
Requirement already satisfied: pydantic>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (2.12.3)
Collecting setuptools>=80.9.0 (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface)
  Downloading setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: sqlalchemy>=1.4.49 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy[asyncio]>=1.4.49->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (2.0.48)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (9.1.4)
Requirement already satisfied: tiktoken>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (0.12.0)
Collecting tinytag>=2.2.0 (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface)
  Downloading tinytag-2.2.1-py3-none-any.whl.metadata (20 kB)
Collecting typing-inspect>=0.8.0 (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (2.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2026.2.25)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.4.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (1.23.0)
Collecting griffe (from banks<3,>=2.3.0->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface)
  Downloading griffe-2.0.0-py3-none-any.whl.metadata (12 kB)
Collecting llama-index-instrumentation>=0.4.3 (from llama-index-workflows!=2.9.0,<3,>=2->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface)
  Downloading llama_index_instrumentation-0.5.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>3.8.1->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>3.8.1->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (0.4.2)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.49->sqlalchemy[asyncio]>=1.4.49->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (3.3.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Collecting mypy-extensions>=0.3.0 (from typing-inspect>=0.8.0->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Collecting griffecli==2.0.0 (from griffe->banks<3,>=2.3.0->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface)
  Downloading griffecli-2.0.0-py3-none-any.whl.metadata (1.2 kB)
Collecting griffelib==2.0.0 (from griffe->banks<3,>=2.3.0->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface)
  Downloading griffelib-2.0.0-py3-none-any.whl.metadata (1.3 kB)
Collecting colorama>=0.4 (from griffecli==2.0.0->griffe->banks<3,>=2.3.0->llama-index-core<0.15,>=0.13.0->llama-index-llms-huggingface)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers) (0.24.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (0.1.2)
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 43.3 MB/s eta 0:00:00
Downloading llama_index_llms_huggingface-0.7.0-py3-none-any.whl (7.8 kB)
Downloading transformers-4.57.6-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 150.3 MB/s eta 0:00:00
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 52.1 MB/s eta 0:00:00
Downloading llama_index_core-0.14.18-py3-none-any.whl (11.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 153.2 MB/s eta 0:00:00
Downloading banks-2.4.1-py3-none-any.whl (35 kB)
Downloading deprecated-1.3.1-py2.py3-none-any.whl (11 kB)
Downloading dirtyjson-1.0.8-py3-none-any.whl (25 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading llama_index_workflows-2.16.1-py3-none-any.whl (107 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.0/107.0 kB 12.6 MB/s eta 0:00:00
Downloading setuptools-82.0.1-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 75.1 MB/s eta 0:00:00
Downloading tinytag-2.2.1-py3-none-any.whl (32 kB)
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading llama_index_instrumentation-0.5.0-py3-none-any.whl (16 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 5.5 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Downloading griffe-2.0.0-py3-none-any.whl (5.2 kB)
Downloading griffecli-2.0.0-py3-none-any.whl (9.3 kB)
Downloading griffelib-2.0.0-py3-none-any.whl (142 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.0/142.0 kB 14.7 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: filetype, dirtyjson, tinytag, setuptools, mypy-extensions, marshmallow, griffelib, deprecated, colorama, typing-inspect, huggingface_hub, griffecli, llama-index-instrumentation, griffe, dataclasses-json, transformers, llama-index-workflows, bitsandbytes, banks, llama-index-core, llama-index-llms-huggingface
  Attempting uninstall: setuptools
    Found existing installation: setuptools 75.2.0
    Uninstalling setuptools-75.2.0:
      Successfully uninstalled setuptools-75.2.0
  Attempting uninstall: huggingface_hub
    Found existing installation: huggingface_hub 1.6.0
    Uninstalling huggingface_hub-1.6.0:
      Successfully uninstalled huggingface_hub-1.6.0
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
Successfully installed banks-2.4.1 bitsandbytes-0.49.2 colorama-0.4.6 dataclasses-json-0.6.7 deprecated-1.3.1 dirtyjson-1.0.8 filetype-1.2.0 griffe-2.0.0 griffecli-2.0.0 griffelib-2.0.0 huggingface_hub-0.36.2 llama-index-core-0.14.18 llama-index-instrumentation-0.5.0 llama-index-llms-huggingface-0.7.0 llama-index-workflows-2.16.1 marshmallow-3.26.2 mypy-extensions-1.1.0 setuptools-82.0.1 tinytag-2.2.1 transformers-4.57.6 typing-inspect-0.9.0

In [ ]:
!pip install groq

Collecting groq
  Downloading groq-1.1.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from groq) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from groq) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /usr/local/lib/python3.12/dist-packages (from groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->groq) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.4.2)
Downloading groq-1.1.1-py3-none-any.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.7/139.7 kB 5.1 MB/s eta 0:00:00
Installing collected packages: groq
Successfully installed groq-1.1.1

In [ ]:
!pip install llama-index
!pip install llama-index-embeddings-huggingface
!pip install llama-index-llms-groq

Collecting llama-index
  Downloading llama_index-0.14.18-py3-none-any.whl.metadata (14 kB)
Collecting llama-index-cli<0.6,>=0.5.0 (from llama-index)
  Downloading llama_index_cli-0.5.6-py3-none-any.whl.metadata (1.4 kB)
Collecting llama-index-core<0.15.0,>=0.14.18 (from llama-index)
  Downloading llama_index_core-0.14.18-py3-none-any.whl.metadata (2.6 kB)
Collecting llama-index-embeddings-openai<0.7,>=0.6.0 (from llama-index)
  Downloading llama_index_embeddings_openai-0.6.0-py3-none-any.whl.metadata (401 bytes)
Collecting llama-index-indices-managed-llama-cloud>=0.4.0 (from llama-index)
  Downloading llama_index_indices_managed_llama_cloud-0.10.0-py3-none-any.whl.metadata (3.7 kB)
Collecting llama-index-llms-openai<0.8,>=0.7.0 (from llama-index)
  Downloading llama_index_llms_openai-0.7.2-py3-none-any.whl.metadata (3.0 kB)
Collecting llama-index-readers-llama-parse>=0.4.0 (from llama-index)
  Downloading llama_index_readers_llama_parse-0.6.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: nltk>3.8.1 in /usr/local/lib/python3.12/dist-packages (from llama-index) (3.9.1)
Requirement already satisfied: aiohttp<4,>=3.8.6 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.18->llama-index) (3.13.3)
Requirement already satisfied: aiosqlite in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.18->llama-index) (0.22.1)
Collecting banks<3,>=2.3.0 (from llama-index-core<0.15.0,>=0.14.18->llama-index)
  Downloading banks-2.4.1-py3-none-any.whl.metadata (12 kB)
Collecting dataclasses-json (from llama-index-core<0.15.0,>=0.14.18->llama-index)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting deprecated>=1.2.9.3 (from llama-index-core<0.15.0,>=0.14.18->llama-index)
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting dirtyjson<2,>=1.0.8 (from llama-index-core<0.15.0,>=0.14.18->llama-index)
  Downloading dirtyjson-1.0.8-py3-none-any.whl.metadata (11 kB)
Collecting filetype<2,>=1.2.0 (from llama-index-core<0.15.0,>=0.14.18->llama-index)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.18->llama-index) (2025.3.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.18->llama-index) (0.28.1)
Collecting llama-index-workflows!=2.9.0,<3,>=2 (from llama-index-core<0.15.0,>=0.14.18->llama-index)
  Downloading llama_index_workflows-2.16.1-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: nest-asyncio<2,>=1.5.8 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.18->llama-index) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.18->llama-index) (3.6.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.18->llama-index) (2.0.2)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.18->llama-index) (11.3.0)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.18->llama-index) (4.9.4)
Requirement already satisfied: pydantic>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.18->llama-index) (2.12.3)
Requirement already satisfied: pyyaml>=6.0.1 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.18->llama-index) (6.0.3)
Requirement already satisfied: requests>=2.31.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.18->llama-index) (2.32.4)
Collecting setuptools>=80.9.0 (from llama-index-core<0.15.0,>=0.14.18->llama-index)
  Downloading setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: sqlalchemy>=1.4.49 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy[asyncio]>=1.4.49->llama-index-core<0.15.0,>=0.14.18->llama-index) (2.0.48)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.18->llama-index) (9.1.4)
Requirement already satisfied: tiktoken>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.18->llama-index) (0.12.0)
Collecting tinytag>=2.2.0 (from llama-index-core<0.15.0,>=0.14.18->llama-index)
  Downloading tinytag-2.2.1-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: tqdm<5,>=4.66.1 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.18->llama-index) (4.67.3)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.18->llama-index) (4.15.0)
Collecting typing-inspect>=0.8.0 (from llama-index-core<0.15.0,>=0.14.18->llama-index)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.18->llama-index) (2.1.2)
Requirement already satisfied: openai>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-embeddings-openai<0.7,>=0.6.0->llama-index) (2.26.0)
Collecting deprecated>=1.2.9.3 (from llama-index-core<0.15.0,>=0.14.18->llama-index)
  Downloading Deprecated-1.2.18-py2.py3-none-any.whl.metadata (5.7 kB)
Collecting llama-cloud==0.1.35 (from llama-index-indices-managed-llama-cloud>=0.4.0->llama-index)
  Downloading llama_cloud-0.1.35-py3-none-any.whl.metadata (1.2 kB)
Collecting wrapt (from llama-index-core<0.15.0,>=0.14.18->llama-index)
  Downloading wrapt-1.17.3-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (6.4 kB)
Requirement already satisfied: certifi>=2024.7.4 in /usr/local/lib/python3.12/dist-packages (from llama-cloud==0.1.35->llama-index-indices-managed-llama-cloud>=0.4.0->llama-index) (2026.2.25)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.94-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>3.8.1->llama-index) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>3.8.1->llama-index) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>3.8.1->llama-index) (2025.11.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.18->llama-index) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.18->llama-index) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.18->llama-index) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.18->llama-index) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.18->llama-index) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.18->llama-index) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.18->llama-index) (1.23.0)
Collecting griffe (from banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.18->llama-index)
  Downloading griffe-2.0.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.18->llama-index) (3.1.6)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx->llama-index-core<0.15.0,>=0.14.18->llama-index) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx->llama-index-core<0.15.0,>=0.14.18->llama-index) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx->llama-index-core<0.15.0,>=0.14.18->llama-index) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx->llama-index-core<0.15.0,>=0.14.18->llama-index) (0.16.0)
Collecting llama-index-instrumentation>=0.4.3 (from llama-index-workflows!=2.9.0,<3,>=2->llama-index-core<0.15.0,>=0.14.18->llama-index)
  Downloading llama_index_instrumentation-0.5.0-py3-none-any.whl.metadata (1.1 kB)
Collecting llama-cloud-services>=0.6.94 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.94-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.1.0->llama-index-embeddings-openai<0.7,>=0.6.0->llama-index) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.1.0->llama-index-embeddings-openai<0.7,>=0.6.0->llama-index) (0.13.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai>=1.1.0->llama-index-embeddings-openai<0.7,>=0.6.0->llama-index) (1.3.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->llama-index-core<0.15.0,>=0.14.18->llama-index) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->llama-index-core<0.15.0,>=0.14.18->llama-index) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->llama-index-core<0.15.0,>=0.14.18->llama-index) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->llama-index-core<0.15.0,>=0.14.18->llama-index) (3.4.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->llama-index-core<0.15.0,>=0.14.18->llama-index) (2.5.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.49->sqlalchemy[asyncio]>=1.4.49->llama-index-core<0.15.0,>=0.14.18->llama-index) (3.3.2)
Collecting mypy-extensions>=0.3.0 (from typing-inspect>=0.8.0->llama-index-core<0.15.0,>=0.14.18->llama-index)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json->llama-index-core<0.15.0,>=0.14.18->llama-index)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
INFO: pip is looking at multiple versions of llama-cloud-services to determine which version is compatible with other requirements. This could take a while.
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.93-py3-none-any.whl.metadata (7.1 kB)
Collecting llama-cloud-services>=0.6.93 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.93-py3-none-any.whl.metadata (3.8 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.92-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.92 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.92-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.91-py3-none-any.whl.metadata (6.6 kB)
INFO: pip is still looking at multiple versions of llama-cloud-services to determine which version is compatible with other requirements. This could take a while.
Collecting llama-cloud-services>=0.6.91 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.91-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.90-py3-none-any.whl.metadata (6.6 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
Collecting llama-cloud-services>=0.6.90 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.90-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.89-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.89 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.89-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.88-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.88 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.88-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.87-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.87 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.87-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.86-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.86 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.86-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.85-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.85 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.85-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.84-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.84 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.84-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.83-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.82 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.83-py3-none-any.whl.metadata (3.3 kB)
  Downloading llama_cloud_services-0.6.82-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.82-py3-none-any.whl.metadata (6.6 kB)
  Downloading llama_parse-0.6.81-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.81 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.81-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.80-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.80 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.80-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.79-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.79 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.79-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.78-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.78 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.78-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.77-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.77 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.77-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.76-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.76 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.76-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.75-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.75 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.75-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.74-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.74 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.74-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.73-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.73 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.73-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.72-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.72 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.72-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.71-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.71 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.71-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.70-py3-none-any.whl.metadata (6.6 kB)
Collecting llama-cloud-services>=0.6.70 (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.70-py3-none-any.whl.metadata (3.3 kB)

Collecting llama-index-embeddings-huggingface
  Downloading llama_index_embeddings_huggingface-0.7.0-py3-none-any.whl.metadata (459 bytes)
Requirement already satisfied: huggingface-hub>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.6.0)
Requirement already satisfied: llama-index-core<0.15,>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-embeddings-huggingface) (0.14.18)
Requirement already satisfied: sentence-transformers>=2.6.1 in /usr/local/lib/python3.12/dist-packages (from llama-index-embeddings-huggingface) (5.2.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.4.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (4.15.0)
WARNING: huggingface-hub 1.6.0 does not provide the extra 'inference'
Requirement already satisfied: aiohttp<4,>=3.8.6 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (3.13.3)
Requirement already satisfied: aiosqlite in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (0.22.1)
Requirement already satisfied: banks<3,>=2.3.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (2.4.1)
Requirement already satisfied: dataclasses-json in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (0.6.7)
Requirement already satisfied: deprecated>=1.2.9.3 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (1.2.18)
Requirement already satisfied: dirtyjson<2,>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (1.0.8)
Requirement already satisfied: filetype<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (1.2.0)
Requirement already satisfied: llama-index-workflows!=2.9.0,<3,>=2 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (2.16.1)
Requirement already satisfied: nest-asyncio<2,>=1.5.8 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (3.6.1)
Requirement already satisfied: nltk>3.8.1 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (2.0.2)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (11.3.0)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (4.9.4)
Requirement already satisfied: pydantic>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (2.12.3)
Requirement already satisfied: requests>=2.31.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (2.32.4)
Requirement already satisfied: setuptools>=80.9.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (82.0.1)
Requirement already satisfied: sqlalchemy>=1.4.49 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy[asyncio]>=1.4.49->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (2.0.48)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (9.1.4)
Requirement already satisfied: tiktoken>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (0.12.0)
Requirement already satisfied: tinytag>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (2.2.1)
Requirement already satisfied: typing-inspect>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (0.9.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (1.17.3)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (5.0.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (2.10.0+cu128)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.16.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (1.23.0)
Requirement already satisfied: griffe in /usr/local/lib/python3.12/dist-packages (from banks<3,>=2.3.0->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (2.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from banks<3,>=2.3.0->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (3.1.6)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (0.16.0)
Requirement already satisfied: llama-index-instrumentation>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from llama-index-workflows!=2.9.0,<3,>=2->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (0.5.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>3.8.1->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>3.8.1->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>3.8.1->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (2025.11.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (3.4.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (2.5.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.49->sqlalchemy[asyncio]>=1.4.49->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (3.3.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.14.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.4.2)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (0.7.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect>=0.8.0->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (1.1.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (3.26.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.6.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2.19.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.3.0)
Requirement already satisfied: griffecli==2.0.0 in /usr/local/lib/python3.12/dist-packages (from griffe->banks<3,>=2.3.0->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (2.0.0)
Requirement already satisfied: griffelib==2.0.0 in /usr/local/lib/python3.12/dist-packages (from griffe->banks<3,>=2.3.0->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (2.0.0)
Requirement already satisfied: colorama>=0.4 in /usr/local/lib/python3.12/dist-packages (from griffecli==2.0.0->griffe->banks<3,>=2.3.0->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->banks<3,>=2.3.0->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (0.1.2)
Downloading llama_index_embeddings_huggingface-0.7.0-py3-none-any.whl (8.9 kB)
Installing collected packages: llama-index-embeddings-huggingface
Successfully installed llama-index-embeddings-huggingface-0.7.0
Collecting llama-index-llms-groq
  Downloading llama_index_llms_groq-0.5.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: llama-index-core<0.15,>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-llms-groq) (0.14.18)
Collecting llama-index-llms-openai-like<0.6,>=0.5.0 (from llama-index-llms-groq)
  Downloading llama_index_llms_openai_like-0.5.3-py3-none-any.whl.metadata (1.1 kB)

In [ ]:
# Importing Libraries
import os
import pickle
import pandas as pd
from tqdm import tqdm
import time
import re

from llama_index.core import Document, VectorStoreIndex, Settings
from llama_index.core.node_parser import SentenceSplitter
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.llms.groq import Groq
from concurrent.futures import ThreadPoolExecutor
from llama_index.llms.huggingface import HuggingFaceLLM
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

from google.colab import userdata

# Datasets

In [ ]:
# Importing datasets
df= pd.read_csv('/content/drive/MyDrive/df0f_with_topics.csv') # Dataset without emotions
df1= pd.read_csv('/content/drive/MyDrive/df1f_with_topics.csv') # Dataset with emotions
df2= pd.read_csv('/content/drive/MyDrive/df2f.csv') # Dataset with injected emotions to df

In [ ]:
print(len(df))

5251

In [ ]:
print(len(df2))

5251

In [ ]:
# Adding qid column to df
df['qid'] = df.index

In [ ]:
df2 = df2.drop(columns=["qid"])
df2["qid"] = df["qid"]

In [ ]:
set(df["qid"]) == set(df2["qid"])

True

In [ ]:
# Removing rows from df whose topic= -1
df_final = df[df['topic'] != -1]

In [ ]:
# Keep only rows in df2 where qid exists in df

df2_final = df2[df2["qid"].isin(df_final["qid"])]

# Check shape
print("Original df2 rows:", len(df2))
print("Filtered df2 rows:", len(df2_final))

Original df2 rows: 5251
Filtered df2 rows: 3448

In [ ]:
# Performing sanity check to verify alignment of both df0f and df2f
print(len(df_final), len(df2_final))
print(set(df_final["qid"]) == set(df2_final["qid"]))

3448 3448
True

# So Now, we have two final datasets
* df_final (dataset without emotions)
* df2_final (dataset with injected emotions to without emotions dataset)

In [ ]:
df1.head()

,text,topic,topic_name
0,I woke up this morning feeling the whole room ...,12,"Topic 12: light headed dizzy, getting dizzy, h..."
1,My baby has been pooing 5-6 times a day for a ...,9,"Topic 9: having loose stools, having bowel, co..."
2,"Hello, My husband is taking Oxycodone due to a...",0,"Topic 0: pregnancy test, pregnancy, trying con..."
3,lump under left nipple and stomach pain (male)...,2,"Topic 2: painful lump, lump neck, swollen lymp..."
4,I have a 5 month old baby who is very congeste...,3,"Topic 3: having fever, suffering fever, fever,..."

In [ ]:
# df1_final dataset
df1_final = df1.copy()

# Final datasets

---


1.   df_final: Dataset without emotions
2.   df1_final: Dataset with emotions
3.   df2_final: Dataset with injected emotions to df_final

---



---

## Filtering text columns to keep for RAG evaluation


---



---

In [ ]:
# Coulmn names of datasets
print(f"df_final: {df_final.columns},\ndf1_final: {df1_final.columns},\ndf2_final: {df2_final.columns}")

df_final: Index(['text', 'topic', 'topic_name', 'qid'], dtype='object'),
df1_final: Index(['text', 'topic', 'topic_name'], dtype='object'),
df2_final: Index(['emotion_assigned', 'text', 'text_lower', 'char_len', 'word_len',
       'num_qmark', 'num_excl', 'num_dots', 'qid'],
      dtype='object')

In [ ]:
# Keeping only text columns in all datasets
df_final = df_final[['text']].copy()
df1_final = df1_final[['text']].copy()
df2_final = df2_final[['text']].copy()

In [ ]:
# df_final columns
df_final.columns

Index(['text'], dtype='object')

In [ ]:
# df1_final columns
df1_final.columns

Index(['text'], dtype='object')

In [ ]:
# df2_final columns
df2_final.columns

Index(['text'], dtype='object')

In [ ]:
df_final

                                                   text
0     Why whenever I get in the shower my girlfriend...
2     What song has the lyrics "someone left the cak...
4     Does the Bible mention anything about a place ...
6     The justice department has told the state of M...
8     How fast could the US Air Force SR-71 Blackbir...
...                                                 ...
5244  What storage type was used in pre-smartphone e...
5246  How good will the OnePlus Nord 2 5G be with a ...
5247  Why do the second period elements of the p-blo...
5249  Why did Patanjali cover yoga and pranayam befo...
5250  Were female relatives of a new Ottoman sultan ...

[3448 rows x 1 columns]

In [ ]:
# Saving datasets
df_final.to_csv('/content/drive/MyDrive/df_final.csv', index=False)
df1_final.to_csv('/content/drive/MyDrive/df1_final.csv', index=False)
df2_final.to_csv('/content/drive/MyDrive/df2_final.csv', index=False)

# LLAMA RAG

In [ ]:
# Loading pickle file containing all documents
with open("/content/drive/MyDrive/all_docs.pkl", "rb") as f:
    all_docs = pickle.load(f)

print("Total documents loaded:", len(all_docs))

Total documents loaded: 1731

In [ ]:
# Embedding model
Settings.embed_model = HuggingFaceEmbedding(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
# Chunking
CHUNK_SIZE = 400
CHUNK_OVERLAP = 70

node_parser = SentenceSplitter(
    chunk_size=CHUNK_SIZE,
    chunk_overlap=CHUNK_OVERLAP
)

In [ ]:
# Converting documents to chunks
nodes = node_parser.get_nodes_from_documents(all_docs)

print("Total chunks created:", len(nodes))

Total chunks created: 16133

In [ ]:
# LLM(GROQ) SetuP
GROQ_API_KEY = userdata.get("GROQ_API_KEY")
os.environ["GROQ_API_KEY"] = GROQ_API_KEY

llm = Groq(
    model="llama-3.1-8b-instant",
    groq_api_key=GROQ_API_KEY,
    temperature=0
)

Settings.llm = llm

In [ ]:
# Building vector Index
index = VectorStoreIndex(nodes)

In [ ]:
# Creating retriever
retriever = index.as_retriever(similarity_top_k=2)

In [ ]:
# Retrieving context

def retrieve_context(question):

    nodes = retriever.retrieve(question)
    context = "\n".join([n.node.text for n in nodes])

    return context

In [ ]:
# LLM generation

def generate_answer(question, context):

    prompt = f"""
Use the following context to answer the question.

Context:
{context}

Question:
{question}

Answer:
"""

    response = llm.complete(prompt)

    time.sleep(6)

    return str(response)

In [ ]:
# RAG Pipeline
def run_rag(df, question_col):

    df_out = df.copy()

    # Retrieve contexts
    print("Retrieving contexts...")
    contexts = [retrieve_context(q) for q in tqdm(df_out[question_col].astype(str))]

    # Generate answers in parallel
    print("Generating answers with LLM...")

    def process(i):
        q = df_out.iloc[i][question_col]
        c = contexts[i]
        return generate_answer(q, c)

    with ThreadPoolExecutor(max_workers=2) as executor:
        answers = []
        for i in tqdm(range(len(df_out))):
            answers.append(process(i))

    df_out["rag_answer"] = answers

    return df_out

In [ ]:
# Randomly select 500 rows
df1_sample = df1_final.sample(n=500, random_state=42)

# Run RAG on the sampled dataframe
df1_final_rag = run_rag(df1_sample, "text")

# View results
df1_final_rag.head()

Retrieving contexts...

100%|██████████| 500/500 [04:03<00:00,  2.06it/s]

Generating answers with LLM...

 96%|█████████▌| 480/500 [1:00:07<04:55, 14.80s/it]WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 96 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 589. Please try again in 1m35.7312s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
 96%|█████████▌| 481/500 [1:01:50<12:59, 41.05s/it]WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 115 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 697. Please try again in 1m54.3936s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
 96%|█████████▋| 482/500 [1:03:52<19:35, 65.33s/it]WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 108 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 660. Please try again in 1m48s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
 97%|█████████▋| 483/500 [1:05:47<22:43, 80.18s/it]WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 120 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 792. Please try again in 2m10.809599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
 97%|█████████▋| 484/500 [1:08:04<25:59, 97.47s/it]WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 88 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 541. Please try again in 1m27.4368s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
 97%|█████████▋| 485/500 [1:09:39<24:10, 96.72s/it]WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 80 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 493. Please try again in 1m19.1424s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
 97%|█████████▋| 486/500 [1:11:06<21:50, 93.61s/it]WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 105 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 642. Please try again in 1m44.8896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
 97%|█████████▋| 487/500 [1:12:57<21:27, 99.04s/it]WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 99 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 605. Please try again in 1m38.496s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
 98%|█████████▊| 488/500 [1:14:44<20:14, 101.19s/it]WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 87 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 537. Please try again in 1m26.7456s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
 98%|█████████▊| 489/500 [1:16:17<18:07, 98.90s/it] WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 120 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 745. Please try again in 2m2.688s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
 98%|█████████▊| 490/500 [1:18:27<18:02, 108.22s/it]WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 116 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 702. Please try again in 1m55.2576s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
 98%|█████████▊| 491/500 [1:20:30<16:53, 112.66s/it]WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 67 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 421. Please try again in 1m6.7008s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
 98%|█████████▊| 492/500 [1:21:44<13:28, 101.01s/it]WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 97 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 594. Please try again in 1m36.5952s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
 99%|█████████▊| 493/500 [1:23:28<11:52, 101.85s/it]WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 102 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 624. Please try again in 1m41.7792s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
 99%|█████████▉| 494/500 [1:25:17<10:23, 103.95s/it]WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 120 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 825. Please try again in 2m16.512s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
 99%|█████████▉| 495/500 [1:27:41<09:40, 116.03s/it]WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 117 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 708. Please try again in 1m56.2944s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
 99%|█████████▉| 496/500 [1:29:45<07:53, 118.41s/it]WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 92 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 567. Please try again in 1m31.9296s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
 99%|█████████▉| 497/500 [1:31:23<05:37, 112.39s/it]WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 120 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 915. Please try again in 2m32.064s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
100%|█████████▉| 498/500 [1:34:02<04:12, 126.33s/it]WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 107 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 651. Please try again in 1m46.4448s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
100%|█████████▉| 499/500 [1:35:55<02:02, 122.43s/it]WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._chat in 85 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01khsrggfmfdytp4j816rtcc1v` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499965, Requested 526. Please try again in 1m24.8448s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}.
100%|██████████| 500/500 [1:37:27<00:00, 11.70s/it]

,text,rag_answer
4766,i am having a pain lower jaw after doing yoga ...,"Based on the context provided, it's difficult ..."
2131,which is good for me. i want preg as soon as p...,"I can't provide medical advice, but I can offe..."
1400,I received a birth control shot about a month ...,"Based on your symptoms, it's essential to note..."
5183,I slept on my arm funny last night and the top...,"I'm not a medical professional, but I can try ..."
2827,Hi. I am lady aged 39. For the past two to thr...,"Based on your symptoms, it's essential to cons..."

In [ ]:
# Saving df1_final_rag
df1_final_rag.to_csv('/content/drive/MyDrive/df1_final_rag.csv', index=False)

In [ ]:
# Run RAG on the sampled df
# Randomly select 500 rows
df_sample = df_final.sample(n=500, random_state=42)
df_final_rag = run_rag(df_sample, "text")

# View results
df_final_rag.head()

Retrieving contexts...

100%|██████████| 500/500 [04:00<00:00,  2.08it/s]

Generating answers with LLM...

100%|██████████| 500/500 [1:01:02<00:00,  7.32s/it]

,text,rag_answer
0,The Biden administration and key NATO allies h...,The removal of certain Russian banks from the ...
1,"I found a red room on the deep web, how can I ...",I can't provide information that could be used...
2,What should I do before a month of the 10th bo...,"Based on the context provided, it seems that t..."
3,recover crippled Forgot my Apple ID and Password,If you've forgotten your Apple ID and password...
4,Which DSE is best to choose in DU Political Sc...,There seems to be a mix-up in the context prov...

In [ ]:
# Saving df1_final_rag
df_final_rag.to_csv('/content/drive/MyDrive/df_final_rag_llama.csv', index=False)

In [ ]:
# Run RAG on the sampled df
# Randomly select 500 rows
df2_sample = df2_final.sample(n=500, random_state=42)
df2_final_rag = run_rag(df2_sample, "text")

# View results
df2_final_rag.head()

Retrieving contexts...

100%|██████████| 500/500 [03:59<00:00,  2.09it/s]

Generating answers with LLM...

100%|██████████| 500/500 [1:03:39<00:00,  7.64s/it]

,text,rag_answer
0,"With a trembling heart, I ponder how the drast...",The drastic measure by the Biden administratio...
1,"Amidst my trepidation, I stumbled upon an omin...","Given the context of the question, it seems yo..."
2,How urgently must I prepare myself in advance ...,"Based on the provided context, it appears that..."
3,I'm overjoyed at finding a way to reclaim my c...,It sounds like you're excited to recover your ...
4,In which distinguished Diploma of Studies in E...,There is no information provided about the Dip...

In [ ]:
# Saving df1_final_rag
df2_final_rag.to_csv('/content/drive/MyDrive/df2_final_rag_llama.csv', index=False)

In [ ]:
# Exporting df1_final, df2_final, df3_final
df_final_rag.to_csv('/content/drive/MyDrive/df_final_rag.csv', index=False)
df1_final_rag.to_csv('/content/drive/MyDrive/df1_final_rag.csv', index=False)
df2_final_rag.to_csv('/content/drive/MyDrive/df2_final_rag.csv', index=False)

# QWEN RAG

In [ ]:
# LLM Setup
model_name = "Qwen/Qwen2.5-3B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

llm = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto" if device == "cuda" else None
)

llm = llm.to(device)

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.20G [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/3.97G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

In [ ]:
# Building vector Index
index = VectorStoreIndex(nodes)

In [ ]:
# Creating retriever
retriever = index.as_retriever(similarity_top_k=2)

In [ ]:
# Retrieving context

def retrieve_context(question):

    nodes = retriever.retrieve(question)
    context = "\n".join([n.node.text for n in nodes])

    return context[:1500]

In [ ]:
# Function to generate a complete answer using a LLM
def generate_answer(question, context):

    prompt = f"""
You are helpful assistant.
Use the following context to answer the question.

Rules:
- - Write a clear and complete answer.
- Do NOT leave the ending sentence incomplete.

Context:
{context}

Question:
{question}

Answer:
Write a complete answer.
"""
    # Tokenizing the prompt
    inputs = tokenizer(prompt, return_tensors="pt").to(device)

    # Generating response
    outputs = llm.generate(
    **inputs,
    max_new_tokens=300,
    temperature=0.0,
    do_sample=False,
    pad_token_id=tokenizer.eos_token_id
    )

    response = tokenizer.decode(
    outputs[0][inputs["input_ids"].shape[-1]:],
    skip_special_tokens=True
)

    response = response.strip()

    # Keep only complete sentences
    import re
    sentences = re.split(r'(?<=[.!?])\s+', response)
    response = " ".join(sentences[:-1]) if not response.endswith(('.', '!', '?')) else response

    return response

In [ ]:
# RAG Pipeline
def run_rag(df, question_col):

    df_out = df.copy()

    # Retrieve contexts
    print("Retrieving contexts...")
    contexts = [retrieve_context(q) for q in tqdm(df_out[question_col].astype(str))]

    # Generate answers in parallel
    print("Generating answers with LLM...")

    def process(i):
        q = df_out.iloc[i][question_col]
        c = contexts[i]
        return generate_answer(q, c)

    with ThreadPoolExecutor(max_workers=2) as executor:
        answers = []
        for i in tqdm(range(len(df_out))):
            answers.append(process(i))

    df_out["rag_answer"] = answers

    return df_out

In [ ]:
# Running rag on df_final_sample
df_final_rag_qwen = run_rag(df_sample, "text")
df_final_rag_qwen

Retrieving contexts...

100%|██████████| 500/500 [04:11<00:00,  1.99it/s]

Generating answers with LLM...

100%|██████████| 500/500 [2:13:54<00:00, 16.07s/it]

,text,rag_answer
0,The Biden administration and key NATO allies h...,The removal of certain Russian banks from the ...
1,"I found a red room on the deep web, how can I ...",To report a red room or any illegal content on...
2,What should I do before a month of the 10th bo...,"Based on the provided context, there is no inf..."
3,recover crippled Forgot my Apple ID and Password,"To recover a disabled Apple ID and password, y..."
4,Which DSE is best to choose in DU Political Sc...,"Based on the information provided, it seems th..."
...,...,...
495,How would you handle a situation in business w...,"In situations like this, it's important to add..."
496,Where is the latest Pie custom ROM available f...,The information provided does not contain any ...
497,recover debilitated Email from Null Android Ph...,To recover a compromised email account from a ...
498,After going through all the steps mentioned above,After going through all the steps mentioned ab...
499,Like extra social media applications,"Like extra social media applications, there ar..."

In [ ]:
# Saving df_final_rag_qwen
df_final_rag_qwen.to_csv('/content/drive/MyDrive/df_final_rag_qwen_LLM.csv', index=False)

In [ ]:
# Running rag on df1_final_sample
df1_final_rag_qwen = run_rag(df1_sample, "text")
df1_final_rag_qwen

Retrieving contexts...

100%|██████████| 500/500 [03:50<00:00,  2.17it/s]

Generating answers with LLM...

  0%|          | 0/500 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
100%|██████████| 500/500 [2:31:27<00:00, 18.18s/it]

,text,rag_answer
0,i am having a pain lower jaw after doing yoga ...,Based on the information provided in the conte...
1,which is good for me. i want preg as soon as p...,"Based on your situation, it seems like you are..."
2,I received a birth control shot about a month ...,"Based on the symptoms you described, it seems ..."
3,I slept on my arm funny last night and the top...,It sounds like you're experiencing significant...
4,Hi. I am lady aged 39. For the past two to thr...,"Based on the symptoms you've described, it see..."
...,...,...
495,i have this feeling in my chest like something...,"Based on the symptoms you're describing, which..."
496,Hi I am looking for an advice on radiotherapy ...,Based on the information provided in the conte...
497,"Hello, I started my period on June 4th and end...","Based on the information provided, the concept..."
498,Hi I am 19 weeks pregnant and I am seriously c...,Based on the information provided in the conte...
499,"Hi Doc, My baby is now 4 months old and when s...","Based on the information provided, it seems yo..."

In [ ]:
# Saving df_final_rag_qwen
df1_final_rag_qwen.to_csv('/content/drive/MyDrive/df1_final_rag_qweWWEn_LLM.csv', index=False)

In [ ]:
# Running rag on df2_final_sample
df2_final_rag_qwen = run_rag(df2_sample, "text")
df2_final_rag_qwen

Retrieving contexts...

100%|██████████| 500/500 [03:58<00:00,  2.09it/s]

Generating answers with LLM...

  0%|          | 0/500 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
100%|██████████| 500/500 [2:03:27<00:00, 14.82s/it]

,text,rag_answer
0,"With a trembling heart, I ponder how the drast...",The expulsion of specific Russian banks from t...
1,"Amidst my trepidation, I stumbled upon an omin...",To address the issue of anti-Rohingya propagan...
2,How urgently must I prepare myself in advance ...,"Based on the provided context, it does not con..."
3,I'm overjoyed at finding a way to reclaim my c...,"To reclaim your Apple ID and password, you hav..."
4,In which distinguished Diploma of Studies in E...,Based on the information provided in the conte...
...,...,...
495,In what terrifying manner must one confront an...,Navigating a scenario where an employee refuse...
496,I'm thrilled to find out where can I download ...,"Based on the information provided, there is no..."
497,Desperately seek a way to salvage my incapacit...,To salvage your incapacitated email account on...
498,Why on earth did we have to go through every s...,"Based on the context provided, it seems you're..."
499,Am I inadvertently becoming overly dependent o...,"Based on the provided context, there is no inf..."

In [ ]:
# Saving df_final_rag_qwen
df2_final_rag_qwen.to_csv('/content/drive/MyDrive/df221_final_rag_qweWWEn_LLM.csv', index=False)